// Hardcoded progression challenges — countries ordered by rank, grouped into
// chunks of 5 with a review challenge after every 4 regular ones.
// DO NOT reorder or modify — player progress in localStorage references these by index.
export const progressionChallenges = [
  { type: "regular", codes: ["in","ru","us","ca","cn"], questionsShown: 5, passPercent: 100 },
  { type: "regular", codes: ["de","id","jp","br","pk"], questionsShown: 5, passPercent: 100 },
  { type: "regular", codes: ["au","ng","gb","fr","ar"], questionsShown: 5, passPercent: 100 },
  { type: "regular", codes: ["bd","it","kz","dz","mx"], questionsShown: 5, passPercent: 100 },
  { type: "review", codes: ["in","ru","us","ca","cn","de","id","jp","br","pk","au","ng","gb","fr","ar","bd","it","kz","dz","mx"], questionsShown: 10, passPercent: 80 },
  { type: "regular", codes: ["cd","ph","sa","es","et"], questionsShown: 5, passPercent: 100 },
  { type: "regular", codes: ["kr","eg","sd","ly","vn"], questionsShown: 5, passPercent: 100 },
  { type: "regular", codes: ["ir","tr","mn","nl","pe"], questionsShown: 5, passPercent: 100 },
  { type: "regular", codes: ["td","ch","ne","pl","tz"], questionsShown: 5, passPercent: 100 },
  { type: "review", codes: ["in","ru","us","ca","cn","de","id","jp","br","pk","au","ng","gb","fr","ar","bd","it","kz","dz","mx","cd","ph","sa","es","et","kr","eg","sd","ly","vn","ir","tr","mn","nl","pe","td","ch","ne","pl","tz"], questionsShown: 10, passPercent: 80 },
  { type: "regular", codes: ["ao","be","ml","th","za"], questionsShown: 5, passPercent: 100 },
  { type: "regular", codes: ["se","co","ie","ke","bo"], questionsShown: 5, passPercent: 100 },
  { type: "regular", codes: ["il","mr","no","at","mm"], questionsShown: 5, passPercent: 100 },
  { type: "regular", codes: ["sg","ae","ve","na","iq"], questionsShown: 5, passPercent: 100 },
  { type: "review", codes: ["in","ru","us","ca","cn","de","id","jp","br","pk","au","ng","gb","fr","ar","bd","it","kz","dz","mx","cd","ph","sa","es","et","kr","eg","sd","ly","vn","ir","tr","mn","nl","pe","td","ch","ne","pl","tz","ao","be","ml","th","za","se","co","ie","ke","bo","il","mr","no","at","mm","sg","ae","ve","na","iq"], questionsShown: 10, passPercent: 80 },
  { type: "regular", codes: ["my","mz","ug","af","cl"], questionsShown: 5, passPercent: 100 },
  { type: "regular", codes: ["dk","uz","zm","ma","ro"], questionsShown: 5, passPercent: 100 },
  { type: "regular", codes: ["so","cf","ss","cz","ua"], questionsShown: 5, passPercent: 100 },
  { type: "regular", codes: ["mg","bw","fi","gh","pt"], questionsShown: 5, passPercent: 100 },
  { type: "review", codes: ["in","ru","us","ca","cn","de","id","jp","br","pk","au","ng","gb","fr","ar","bd","it","kz","dz","mx","cd","ph","sa","es","et","kr","eg","sd","ly","vn","ir","tr","mn","nl","pe","td","ch","ne","pl","tz","ao","be","ml","th","za","se","co","ie","ke","bo","il","mr","no","at","mm","sg","ae","ve","na","iq","my","mz","ug","af","cl","dk","uz","zm","ma","ro","so","cf","ss","cz","ua","mg","bw","fi","gh","pt"], questionsShown: 10, passPercent: 80 },
  { type: "regular", codes: ["ye","ci","np","nz","cm"], questionsShown: 5, passPercent: 100 },
  { type: "regular", codes: ["tm","gr","pg","qa","hu"], questionsShown: 5, passPercent: 100 },
  { type: "regular", codes: ["cu","kp","sy","bf","kw"], questionsShown: 5, passPercent: 100 },
  { type: "regular", codes: ["py","lk","zw","mw","sk"], questionsShown: 5, passPercent: 100 },
  { type: "review", codes: ["in","ru","us","ca","cn","de","id","jp","br","pk","au","ng","gb","fr","ar","bd","it","kz","dz","mx","cd","ph","sa","es","et","kr","eg","sd","ly","vn","ir","tr","mn","nl","pe","td","ch","ne","pl","tz","ao","be","ml","th","za","se","co","ie","ke","bo","il","mr","no","at","mm","sg","ae","ve","na","iq","my","mz","ug","af","cl","dk","uz","zm","ma","ro","so","cf","ss","cz","ua","mg","bw","fi","gh","pt","ye","ci","np","nz","cm","tm","gr","pg","qa","hu","cu","kp","sy","bf","kw","py","lk","zw","mw","sk"], questionsShown: 10, passPercent: 80 },
  { type: "regular", codes: ["do","ec","om","cg","bg"], questionsShown: 5, passPercent: 100 },
  { type: "regular", codes: ["gt","sn","lu","kh","pa"], questionsShown: 5, passPercent: 100 },
  { type: "regular", codes: ["hr","gn","ga","lt","rw"], questionsShown: 5, passPercent: 100 },
  { type: "regular", codes: ["bj","az","bi","tn","uy"], questionsShown: 5, passPercent: 100 },
  { type: "review", codes: ["in","ru","us","ca","cn","de","id","jp","br","pk","au","ng","gb","fr","ar","bd","it","kz","dz","mx","cd","ph","sa","es","et","kr","eg","sd","ly","vn","ir","tr","mn","nl","pe","td","ch","ne","pl","tz","ao","be","ml","th","za","se","co","ie","ke","bo","il","mr","no","at","mm","sg","ae","ve","na","iq","my","mz","ug","af","cl","dk","uz","zm","ma","ro","so","cf","ss","cz","ua","mg","bw","fi","gh","pt","ye","ci","np","nz","cm","tm","gr","pg","qa","hu","cu","kp","sy","bf","kw","py","lk","zw","mw","sk","do","ec","om","cg","bg","gt","sn","lu","kh","pa","hr","gn","ga","lt","rw","bj","az","bi","tn","uy"], questionsShown: 10, passPercent: 80 },
  { type: "regular", codes: ["ht","rs","la","by","gy"], questionsShown: 5, passPercent: 100 },
  { type: "regular", codes: ["jo","cr","kg","si","sr"], questionsShown: 5, passPercent: 100 },
  { type: "regular", codes: ["tj","lv","hn","bh","ni"], questionsShown: 5, passPercent: 100 },
  { type: "regular", codes: ["ee","sv","er","sl","tg"], questionsShown: 5, passPercent: 100 },
  { type: "review", codes: ["in","ru","us","ca","cn","de","id","jp","br","pk","au","ng","gb","fr","ar","bd","it","kz","dz","mx","cd","ph","sa","es","et","kr","eg","sd","ly","vn","ir","tr","mn","nl","pe","td","ch","ne","pl","tz","ao","be","ml","th","za","se","co","ie","ke","bo","il","mr","no","at","mm","sg","ae","ve","na","iq","my","mz","ug","af","cl","dk","uz","zm","ma","ro","so","cf","ss","cz","ua","mg","bw","fi","gh","pt","ye","ci","np","nz","cm","tm","gr","pg","qa","hu","cu","kp","sy","bf","kw","py","lk","zw","mw","sk","do","ec","om","cg","bg","gt","sn","lu","kh","pa","hr","gn","ga","lt","rw","bj","az","bi","tn","uy","ht","rs","la","by","gy","jo","cr","kg","si","sr","tj","lv","hn","bh","ni","ee","sv","er","sl","tg"], questionsShown: 10, passPercent: 80 },
  { type: "regular", codes: ["cy","lr","is","ba","ge"], questionsShown: 5, passPercent: 100 },
  { type: "regular", codes: ["tt","am","al","mt","lb"], questionsShown: 5, passPercent: 100 },
  { type: "regular", codes: ["jm","md","bn","bt","gw"], questionsShown: 5, passPercent: 100 },
  { type: "regular", codes: ["mu","mk","ls","bs","sb"], questionsShown: 5, passPercent: 100 },
  { type: "review", codes: ["in","ru","us","ca","cn","de","id","jp","br","pk","au","ng","gb","fr","ar","bd","it","kz","dz","mx","cd","ph","sa","es","et","kr","eg","sd","ly","vn","ir","tr","mn","nl","pe","td","ch","ne","pl","tz","ao","be","ml","th","za","se","co","ie","ke","bo","il","mr","no","at","mm","sg","ae","ve","na","iq","my","mz","ug","af","cl","dk","uz","zm","ma","ro","so","cf","ss","cz","ua","mg","bw","fi","gh","pt","ye","ci","np","nz","cm","tm","gr","pg","qa","hu","cu","kp","sy","bf","kw","py","lk","zw","mw","sk","do","ec","om","cg","bg","gt","sn","lu","kh","pa","hr","gn","ga","lt","rw","bj","az","bi","tn","uy","ht","rs","la","by","gy","jo","cr","kg","si","sr","tj","lv","hn","bh","ni","ee","sv","er","sl","tg","cy","lr","is","ba","ge","tt","am","al","mt","lb","jm","md","bn","bt","gw","mu","mk","ls","bs","sb"], questionsShown: 10, passPercent: 80 },
  { type: "regular", codes: ["gm","gq","dj","bz","mc"], questionsShown: 5, passPercent: 100 },
  { type: "regular", codes: ["fj","tl","li","sz","me"], questionsShown: 5, passPercent: 100 },
  { type: "regular", codes: ["bb","mv","km","vu","ad"], questionsShown: 5, passPercent: 100 },
  { type: "regular", codes: ["cv","ws","lc","st","ki"], questionsShown: 5, passPercent: 100 },
  { type: "review", codes: ["in","ru","us","ca","cn","de","id","jp","br","pk","au","ng","gb","fr","ar","bd","it","kz","dz","mx","cd","ph","sa","es","et","kr","eg","sd","ly","vn","ir","tr","mn","nl","pe","td","ch","ne","pl","tz","ao","be","ml","th","za","se","co","ie","ke","bo","il","mr","no","at","mm","sg","ae","ve","na","iq","my","mz","ug","af","cl","dk","uz","zm","ma","ro","so","cf","ss","cz","ua","mg","bw","fi","gh","pt","ye","ci","np","nz","cm","tm","gr","pg","qa","hu","cu","kp","sy","bf","kw","py","lk","zw","mw","sk","do","ec","om","cg","bg","gt","sn","lu","kh","pa","hr","gn","ga","lt","rw","bj","az","bi","tn","uy","ht","rs","la","by","gy","jo","cr","kg","si","sr","tj","lv","hn","bh","ni","ee","sv","er","sl","tg","cy","lr","is","ba","ge","tt","am","al","mt","lb","jm","md","bn","bt","gw","mu","mk","ls","bs","sb","gm","gq","dj","bz","mc","fj","tl","li","sz","me","bb","mv","km","vu","ad","cv","ws","lc","st","ki"], questionsShown: 10, passPercent: 80 },
  { type: "regular", codes: ["ag","dm","to","fm","sm"], questionsShown: 5, passPercent: 100 },
  { type: "regular", codes: ["sc","pw","vc","gd","kn"], questionsShown: 5, passPercent: 100 },
  { type: "regular", codes: ["mh","tv","nr"], questionsShown: 3, passPercent: 100 },
  { type: "review", codes: ["in","ru","us","ca","cn","de","id","jp","br","pk","au","ng","gb","fr","ar","bd","it","kz","dz","mx","cd","ph","sa","es","et","kr","eg","sd","ly","vn","ir","tr","mn","nl","pe","td","ch","ne","pl","tz","ao","be","ml","th","za","se","co","ie","ke","bo","il","mr","no","at","mm","sg","ae","ve","na","iq","my","mz","ug","af","cl","dk","uz","zm","ma","ro","so","cf","ss","cz","ua","mg","bw","fi","gh","pt","ye","ci","np","nz","cm","tm","gr","pg","qa","hu","cu","kp","sy","bf","kw","py","lk","zw","mw","sk","do","ec","om","cg","bg","gt","sn","lu","kh","pa","hr","gn","ga","lt","rw","bj","az","bi","tn","uy","ht","rs","la","by","gy","jo","cr","kg","si","sr","tj","lv","hn","bh","ni","ee","sv","er","sl","tg","cy","lr","is","ba","ge","tt","am","al","mt","lb","jm","md","bn","bt","gw","mu","mk","ls","bs","sb","gm","gq","dj","bz","mc","fj","tl","li","sz","me","bb","mv","km","vu","ad","cv","ws","lc","st","ki","ag","dm","to","fm","sm","sc","pw","vc","gd","kn","mh","tv","nr"], questionsShown: 10, passPercent: 80 },
];

